# 当 push 到 main 分支时自动部署 Hexo 到 GitHub Pages
name: 自动部署器

on:
  push:
    branches:
      - main    # ← 如果你的源码在 main，就不用改

  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: 检查分支
        uses: actions/checkout@v4
        with:
          ref: main

      # 2. 安装 Node
      - name: 安装 Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"    # 建议 Node 18 或 20

      # 3. 安装 Hexo CLI
      - name: 安装 Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g

      # 4. 缓存 node_modules
      - name: 缓存 Hexo
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      # 5. 安装依赖（如果缓存未命中）
      - name: 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install

      # 6. 生成静态文件
      - name: 生成静态文件
        run: |
          hexo clean
          hexo generate

      # 7. 部署到 GitHub Pages
      - name: 部署
        run: |
          cd ./public
          git init
          git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
          git config --global user.email "${{ secrets.GITHUBEMAIL }}"
          git add .
          git commit -m "${{ github.event.head_commit.message }} $(date '+%Y-%m-%d %H:%M:%S') Updated By GitHub Actions"
          git push --force --quiet "https://${{ secrets.GITHUBUSERNAME }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ secrets.GITHUBUSERNAME }}/${{ secrets.GITHUBUSERNAME }}.github.io.git" master:master
